### ISSUE TITLE
i can't see the whole policy tree.

### ISSUE THREAD

**Issue by lswjmm** [Dimensiondog/Historica#3]
i can't see the initial policies escept"civic tree".is it i use a wrong version? or it has something wrong? what's more,this mod is really fan!

**Comment by Dimensiondog** [comment]
what version are you on?

**Comment by Dimensiondog** [comment]
It works fine for me on the latest version so im going to close this.

**Comment by lswjmm** [comment]
v4.2.2

**Comment by lswjmm** [comment]
which is the latest version?
