### ISSUE TITLE
Is there anyway to fix this?

### ISSUE THREAD

**Issue by ArthurWarden** [Dimensiondog/Historica#5]
Road's unique "Costs [1] gold per turn when in your territory" is deprecated as of 4.3.9, replace with "Costs [1] [stats] per turn when in your territory"
Railroad's unique "Costs [2] gold per turn when in your territory" is deprecated as of 4.3.9, replace with "Costs [2] [stats] per turn when in your territory"
Assyria's colors do not contrast enough - it is unreadable!
Suggested colors: 
		"outerColor": [250, 234, 180],
		"innerColor": [190, 107, 5],
Greece's colors do not contrast enough - it is unreadable!
Suggested colors: 
		"outerColor": [188, 234, 234],
		"innerColor": [61, 127, 224],
India's colors do not contrast enough - it is unreadable!
Suggested colors: 
		"outerColor": [14, 113, 4],
		"innerColor": [255, 163, 71],
The Netherlands's colors do not contrast enough - it is unreadable!
Suggested colors: 
		"outerColor": [216, 122, 0],
		"innerColor": [255, 255, 255],
Ethiopia's colors do not contrast enough - it is unreadable!
Suggested colors: 
		"outerColor": [18, 66, 22],
		"innerColor": [255, 56, 56],
Hanoi's colors do not contrast enough - it is unreadable!
Suggested colors: 
		"outerColor": [0, 0, 0],
		"innerColor": [51, 51, 255],
Kabul's colors do not contrast enough - it is unreadable!
Suggested colors: 
		"outerColor": [0, 0, 0],
		"innerColor": [168, 38, 102],
Barbarians's colors do not contrast enough - it is unreadable!
Suggested colors: 
		"outerColor": [0, 0, 0],
		"innerColor": [185, 12, 12],
Great Artist's unique "Can start an [8]-turn golden age" is deprecated as of 4.5.3, replace with "Empire enters a [8]-turn Golden Age <by consuming this unit>"
Great Artist's unique "Can construct [Landmark]" is deprecated as of 4.5.2, replace with "Can instantly construct a [Landmark] improvement <by consuming this unit>"
Great Scientist's unique "Can construct [Academy]" is deprecated as of 4.5.2, replace with "Can instantly construct a [Academy] improvement <by consuming this unit>"
Great Merchant's unique "Can construct [Customs house]" is deprecated as of 4.5.2, replace with "Can instantly construct a [Customs house] improvement <by consuming this unit>"
Great Engineer's unique "Can construct [Manufactory]" is deprecated as of 4.5.2, replace with "Can instantly construct a [Manufactory] improvement <by consuming this unit>"
Great Prophet's unique "Can construct [Holy site] <if it hasn't used other actions yet>" is deprecated as of 4.5.2, replace with "Can instantly construct a [Holy site] improvement <by consuming this unit>"
Great General's unique "Can start an [8]-turn golden age" is deprecated as of 4.5.3, replace with "Empire enters a [8]-turn Golden Age <by consuming this unit>"
Great General's unique "Can construct [Citadel]" is deprecated as of 4.5.2, replace with "Can instantly construct a [Citadel] improvement <by consuming this unit>"
Khan's unique "Can start an [8]-turn golden age" is deprecated as of 4.5.3, replace with "Empire enters a [8]-turn Golden Age <by consuming this unit>"
Khan's unique "Can construct [Citadel]" is deprecated as of 4.5.2, replace with "Can instantly construct a [Citadel] improvement <by consuming this unit>"
Monarchy's unique "[+2 Food, +2 Happiness] [in capital]]" looks like it may be a misspelling of:
	"[stats] [cityFilter]"
Ceremony's unique "[+3]% Growth [in all cities]" looks like it may be a misspelling of:
	"[relativeAmount]% growth [cityFilter]"
	"+[amount]% growth [cityFilter]" (Deprecated)
Majesty's unique "[+3]% Growth [in all cities]" looks like it may be a misspelling of:
	"[relativeAmount]% growth [cityFilter]"
	"+[amount]% growth [cityFilter]" (Deprecated)
Crown Guard's unique "[+3]% Growth [in all cities]" looks like it may be a misspelling of:
	"[relativeAmount]% growth [cityFilter]"
	"+[amount]% growth [cityFilter]" (Deprecated)
Grandiose's unique "[+3]% Growth [in all cities]" looks like it may be a misspelling of:
	"[relativeAmount]% growth [cityFilter]"
	"+[amount]% growth [cityFilter]" (Deprecated)
State Religion's unique "[+3]% Growth [in all cities]" looks like it may be a misspelling of:
	"[relativeAmount]% growth [cityFilter]"
	"+[amount]% growth [cityFilter]" (Deprecated)

**Comment by Dimensiondog** [comment]
Hi sorry for the late response. I'm not planning on updating the mod until i fix it until I fix my computer. Fortunately I may be able to fix it in the next couple of weeks and then fix the mod.

**Comment by Dimensiondog** [comment]
Will fix on Wednesday.

**Comment by ArthurWarden** [comment]
> Will fix on Wednesday.

Thank you for your hard work. I never tried your mod before so, i'm looking forward to it.

**Comment by Dimensiondog** [comment]
Done, Enjoy the mod.
